#!/bin/bash

# Affiche les connexions Internet (TCP/UDP) en écoute
echo "Active Internet connections (only servers)"
ss -ltunp

# Affiche les sockets UNIX en écoute
echo "Active UNIX domain sockets (only servers)"
ss -lxp
