#!/bin/bash
# Config an unbuntu server with localhost -> 127.0.0.2 and facebook.com -> 8.8.8.8

HOSTS_FILE="/etc/hosts"
BACKUP_FILE="/etc/hosts.bak"

# Display error message and exit
error_exit() {
    echo "$1" >&2
    exit 1
}

# Check root privileges
if [ "$EUID" -ne 0 ]; then
  error_exit "Script must be used as root (sudo)."
fi

# Restore save if user pass --reset
if [ "$1" == "--reset" ]; then
    if [ -f "$BACKUP_FILE" ]; then
        cp "$BACKUP_FILE" "$HOSTS_FILE"
        echo "Fichier $HOSTS_FILE restauré depuis $BACKUP_FILE."
    else
        error_exit "Aucune sauvegarde trouvée. Impossible de restaurer."
    fi
    exit 0
fi

# Save file if it doesn't already exists
if [ ! -f "$BACKUP_FILE" ]; then
    cp "$HOSTS_FILE" "$BACKUP_FILE"
    echo "Sauvegarde créée dans $BACKUP_FILE."
fi

# Deletes existing entries
sed -i '/127.0.0.1\s\+localhost/d' "$HOSTS_FILE"
sed -i '/facebook.com/d' "$HOSTS_FILE"

# Add new entries
echo "127.0.0.2 localhost" >> "$HOSTS_FILE"
echo "8.8.8.8 facebook.com" >> "$HOSTS_FILE"

echo "Résolutions ajoutées avec succès :"
echo "  localhost    → 127.0.0.2"
echo "  facebook.com → 8.8.8.8"

# Check result
ping -c 1 localhost
ping -c 1 facebook.com
